/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as PingRouteImport } from './routes/ping'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProtectedBalancesRouteImport } from './routes/_protected/balances'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedExpensesRouteImport } from './routes/_protected/expenses'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBalancesRoute = ProtectedBalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExpensesRoute = ProtectedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/ping': typeof PingRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/balances': typeof ProtectedBalancesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/expenses': typeof ProtectedExpensesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/ping': typeof PingRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/balances': typeof ProtectedBalancesRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/expenses': typeof ProtectedExpensesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/ping': typeof PingRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/_protected/balances': typeof ProtectedBalancesRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/expenses': typeof ProtectedExpensesRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/ping'
    | '/register'
    | '/setup'
    | '/balances'
    | '/dashboard'
    | '/expenses'
    | '/settings'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/ping'
    | '/register'
    | '/setup'
    | '/balances'
    | '/dashboard'
    | '/expenses'
    | '/settings'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/logout'
    | '/ping'
    | '/register'
    | '/setup'
    | '/_protected/balances'
    | '/_protected/dashboard'
    | '/_protected/expenses'
    | '/_protected/settings'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PingRoute: typeof PingRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ping': {
      id: '/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/balances': {
      id: '/_protected/balances'
      path: '/balances'
      fullPath: '/balances'
      preLoaderRoute: typeof ProtectedBalancesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/expenses': {
      id: '/_protected/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ProtectedExpensesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedBalancesRoute: typeof ProtectedBalancesRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedExpensesRoute: typeof ProtectedExpensesRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBalancesRoute: ProtectedBalancesRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedExpensesRoute: ProtectedExpensesRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PingRoute: PingRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
